"""Add new permissioning stuff

Revision ID: 65407d6d000a
Revises: 5945d8081a95
Create Date: 2018-05-09 21:39:24.743696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65407d6d000a'
down_revision = '5945d8081a95'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=25), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('default', sa.Enum('Undefined', 'No', 'Yes', 'Never', 'Always', name='permissionlevel'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    op.create_table('categories_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('Undefined', 'No', 'Yes', 'Never', 'Always', name='permissionlevel'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_permissions_parent_id_categories')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_categories_permissions_permission_id_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories_permissions'))
    )
    op.create_table('groups_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('Undefined', 'No', 'Yes', 'Never', 'Always', name='permissionlevel'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['groups.id'], name=op.f('fk_groups_permissions_parent_id_groups')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_groups_permissions_permission_id_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups_permissions'))
    )
    op.create_table('users_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('Undefined', 'No', 'Yes', 'Never', 'Always', name='permissionlevel'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_users_permissions_parent_id_users')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_users_permissions_permission_id_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_permissions'))
    )
    op.create_table('forums_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Enum('Undefined', 'No', 'Yes', 'Never', 'Always', name='permissionlevel'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['forums.id'], name=op.f('fk_forums_permissions_parent_id_forums')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_forums_permissions_permission_id_permissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forums_permissions'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.drop_table('forums_permissions')
    op.drop_table('users_permissions')
    op.drop_table('groups_permissions')
    op.drop_table('categories_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
