"""Add when_moderator toggle

Revision ID: 3af252def18c
Revises: 65407d6d000a
Create Date: 2018-05-11 19:45:56.069642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af252def18c'
down_revision = '65407d6d000a'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when_moderator', sa.Boolean(), nullable=False))

    with op.batch_alter_table('forums_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when_moderator', sa.Boolean(), nullable=False))

    with op.batch_alter_table('groups_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when_moderator', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('when_moderator', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_permissions', schema=None) as batch_op:
        batch_op.drop_column('when_moderator')

    with op.batch_alter_table('groups_permissions', schema=None) as batch_op:
        batch_op.drop_column('when_moderator')

    with op.batch_alter_table('forums_permissions', schema=None) as batch_op:
        batch_op.drop_column('when_moderator')

    with op.batch_alter_table('categories_permissions', schema=None) as batch_op:
        batch_op.drop_column('when_moderator')

    # ### end Alembic commands ###
